/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pricing/black-scholes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Black Scholes */
        post: operations["black_scholes_api_v1_pricing_black_scholes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pricing/implied-volatility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Implied Volatility */
        post: operations["implied_volatility_api_v1_pricing_implied_volatility_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pricing/bond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bond */
        post: operations["bond_api_v1_pricing_bond_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pricing/yield-curve/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bootstrap */
        post: operations["bootstrap_api_v1_pricing_yield_curve_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/var/parametric": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parametric Var */
        post: operations["parametric_var_api_v1_risk_var_parametric_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/var/historical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Historical Var */
        post: operations["historical_var_api_v1_risk_var_historical_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/var/monte-carlo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Monte Carlo Var */
        post: operations["monte_carlo_var_api_v1_risk_var_monte_carlo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stress-test/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_v1_stress_test_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stress-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Stress Test */
        post: operations["run_stress_test_api_v1_stress_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optimize */
        post: operations["optimize_api_v1_portfolio_optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/frontier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Frontier */
        post: operations["frontier_api_v1_portfolio_frontier_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetClass
         * @enum {string}
         */
        AssetClass: "equity" | "fixed_income" | "credit" | "commodity" | "real_estate" | "fx" | "cash";
        /** BlackScholesRequest */
        BlackScholesRequest: {
            /** Spot */
            spot: number;
            /** Strike */
            strike: number;
            /**
             * Time To Expiry
             * @description Years
             */
            time_to_expiry: number;
            /**
             * Rate
             * @description Continuously compounded risk-free rate
             */
            rate: number;
            /**
             * Dividend Yield
             * @default 0
             */
            dividend_yield?: number;
            /** @default call */
            option_type?: components["schemas"]["OptionType"];
            /**
             * Volatility
             * @description Annualised, 0.2 = 20%
             */
            volatility: number;
        };
        /** BlackScholesResponse */
        BlackScholesResponse: {
            /** Price */
            price: number;
            /** D1 */
            d1: number;
            /** D2 */
            d2: number;
            /** Delta */
            delta: number;
            /** Gamma */
            gamma: number;
            /**
             * Vega
             * @description Per 1.00 change in volatility
             */
            vega: number;
            /**
             * Theta
             * @description Per year
             */
            theta: number;
            /**
             * Rho
             * @description Per 1.00 change in rate
             */
            rho: number;
        };
        /** BondRequest */
        BondRequest: {
            /**
             * Face
             * @default 100
             */
            face?: number;
            /**
             * Coupon Rate
             * @description Annual, 0.05 = 5%
             */
            coupon_rate: number;
            /** Maturity Years */
            maturity_years: number;
            /**
             * Frequency
             * @default 2
             * @enum {integer}
             */
            frequency?: 1 | 2 | 4 | 12;
            /** @default periodic */
            compounding?: components["schemas"]["Compounding"];
            /** Ytm */
            ytm?: number | null;
            /** Price */
            price?: number | null;
        };
        /** BondResponse */
        BondResponse: {
            /** Price */
            price: number;
            /** Ytm */
            ytm: number;
            /** Macaulay Duration */
            macaulay_duration: number;
            /** Modified Duration */
            modified_duration: number;
            /** Convexity */
            convexity: number;
            /** Cash Flows */
            cash_flows: components["schemas"]["CashFlowOut"][];
        };
        /** BootstrapRequest */
        BootstrapRequest: {
            /** Instruments */
            instruments: components["schemas"]["CurveInstrumentIn"][];
            /**
             * Frequency
             * @default 2
             * @enum {integer}
             */
            frequency?: 1 | 2 | 4 | 12;
            /**
             * Face
             * @default 100
             */
            face?: number;
        };
        /** BootstrapResponse */
        BootstrapResponse: {
            /** Points */
            points: components["schemas"]["ZeroPointOut"][];
        };
        /** CashFlowOut */
        CashFlowOut: {
            /** Time */
            time: number;
            /** Amount */
            amount: number;
            /** Present Value */
            present_value: number;
        };
        /**
         * Compounding
         * @enum {string}
         */
        Compounding: "periodic" | "continuous";
        /** CurveInstrumentIn */
        CurveInstrumentIn: {
            /** Maturity */
            maturity: number;
            /**
             * Coupon Rate
             * @default 0
             */
            coupon_rate?: number;
            /** Price */
            price: number;
        };
        /**
         * Distribution
         * @enum {string}
         */
        Distribution: "normal" | "student_t";
        /** FrontierRequest */
        FrontierRequest: {
            /** Assets */
            assets: string[];
            /**
             * Expected Returns
             * @description Annualised
             */
            expected_returns?: number[] | null;
            /**
             * Covariance
             * @description Annualised
             */
            covariance?: number[][] | null;
            /**
             * Returns
             * @description Periodic returns, T rows x N columns; annualised internally
             */
            returns?: number[][] | null;
            /**
             * Periods Per Year
             * @default 252
             * @enum {integer}
             */
            periods_per_year?: 12 | 52 | 252;
            /**
             * Risk Free Rate
             * @default 0
             */
            risk_free_rate?: number;
            /**
             * Long Only
             * @default true
             */
            long_only?: boolean;
            /** Max Weight */
            max_weight?: number | null;
            /**
             * N Points
             * @default 50
             */
            n_points?: number;
        };
        /** FrontierResponse */
        FrontierResponse: {
            /** Points */
            points: components["schemas"]["PortfolioOut"][];
            min_variance: components["schemas"]["PortfolioOut"];
            tangency: components["schemas"]["PortfolioOut"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoricalVaRRequest */
        HistoricalVaRRequest: {
            /** Positions */
            positions: components["schemas"]["Position"][];
            /**
             * Returns
             * @description Daily returns, T rows x N columns in the same order as positions
             */
            returns: number[][];
            /**
             * Confidence
             * @description VaR confidence level, e.g. 0.99
             * @default 0.99
             */
            confidence?: number;
            /**
             * Horizon Days
             * @default 1
             */
            horizon_days?: number;
        };
        /** ImpliedVolRequest */
        ImpliedVolRequest: {
            /** Spot */
            spot: number;
            /** Strike */
            strike: number;
            /**
             * Time To Expiry
             * @description Years
             */
            time_to_expiry: number;
            /**
             * Rate
             * @description Continuously compounded risk-free rate
             */
            rate: number;
            /**
             * Dividend Yield
             * @default 0
             */
            dividend_yield?: number;
            /** @default call */
            option_type?: components["schemas"]["OptionType"];
            /** Market Price */
            market_price: number;
        };
        /** ImpliedVolResponse */
        ImpliedVolResponse: {
            /** Implied Volatility */
            implied_volatility: number;
        };
        /** MonteCarloVaRRequest */
        MonteCarloVaRRequest: {
            /** Positions */
            positions: components["schemas"]["Position"][];
            /**
             * Covariance
             * @description Daily return covariance matrix (N x N)
             */
            covariance: number[][];
            /**
             * Mean Returns
             * @description Daily mean returns; omitted means zero drift
             */
            mean_returns?: number[] | null;
            /**
             * Confidence
             * @description VaR confidence level, e.g. 0.99
             * @default 0.99
             */
            confidence?: number;
            /**
             * Horizon Days
             * @default 1
             */
            horizon_days?: number;
            /**
             * N Sims
             * @default 10000
             */
            n_sims?: number;
            /** @default normal */
            distribution?: components["schemas"]["Distribution"];
            /**
             * Degrees Of Freedom
             * @default 5
             */
            degrees_of_freedom?: number;
            /** Seed */
            seed?: number | null;
        };
        /** OptimizeRequest */
        OptimizeRequest: {
            /** Assets */
            assets: string[];
            /**
             * Expected Returns
             * @description Annualised
             */
            expected_returns?: number[] | null;
            /**
             * Covariance
             * @description Annualised
             */
            covariance?: number[][] | null;
            /**
             * Returns
             * @description Periodic returns, T rows x N columns; annualised internally
             */
            returns?: number[][] | null;
            /**
             * Periods Per Year
             * @default 252
             * @enum {integer}
             */
            periods_per_year?: 12 | 52 | 252;
            /**
             * Risk Free Rate
             * @default 0
             */
            risk_free_rate?: number;
            /**
             * Long Only
             * @default true
             */
            long_only?: boolean;
            /** Max Weight */
            max_weight?: number | null;
            /**
             * Objective
             * @default max_sharpe
             * @enum {string}
             */
            objective?: "min_variance" | "max_sharpe" | "target_return";
            /** Target Return */
            target_return?: number | null;
        };
        /**
         * OptionType
         * @enum {string}
         */
        OptionType: "call" | "put";
        /** ParametricVaRRequest */
        ParametricVaRRequest: {
            /** Positions */
            positions: components["schemas"]["Position"][];
            /**
             * Covariance
             * @description Daily return covariance matrix (N x N)
             */
            covariance: number[][];
            /**
             * Mean Returns
             * @description Daily mean returns; omitted means zero drift
             */
            mean_returns?: number[] | null;
            /**
             * Confidence
             * @description VaR confidence level, e.g. 0.99
             * @default 0.99
             */
            confidence?: number;
            /**
             * Horizon Days
             * @default 1
             */
            horizon_days?: number;
        };
        /** PortfolioOut */
        PortfolioOut: {
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** Expected Return */
            expected_return: number;
            /** Volatility */
            volatility: number;
            /** Sharpe */
            sharpe: number | null;
        };
        /** Position */
        Position: {
            /** Name */
            name: string;
            /**
             * Value
             * @description Signed currency exposure; negative for shorts
             */
            value: number;
        };
        /** ScenarioOut */
        ScenarioOut: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Shocks */
            shocks: {
                [key: string]: number;
            };
        };
        /** StressLineOut */
        StressLineOut: {
            /** Name */
            name: string;
            asset_class: components["schemas"]["AssetClass"];
            /** Value Before */
            value_before: number;
            /** Shock */
            shock: number;
            /** Pnl */
            pnl: number;
            /** Value After */
            value_after: number;
        };
        /** StressPositionIn */
        StressPositionIn: {
            /** Name */
            name: string;
            asset_class: components["schemas"]["AssetClass"];
            /** Value */
            value: number;
        };
        /** StressTestRequest */
        StressTestRequest: {
            /** Positions */
            positions: components["schemas"]["StressPositionIn"][];
            /**
             * Scenario
             * @description Preset scenario key
             */
            scenario?: string | null;
            /**
             * Custom Shocks
             * @description Asset-class returns, e.g. {'equity': -0.3}
             */
            custom_shocks?: {
                [key: string]: number;
            } | null;
        };
        /** StressTestResponse */
        StressTestResponse: {
            /** Scenario */
            scenario: string;
            /** Lines */
            lines: components["schemas"]["StressLineOut"][];
            /** Value Before */
            value_before: number;
            /** Value After */
            value_after: number;
            /** Pnl */
            pnl: number;
            /** Pnl Pct */
            pnl_pct: number;
        };
        /** VaRResponse */
        VaRResponse: {
            /** Method */
            method: string;
            /** Confidence */
            confidence: number;
            /** Horizon Days */
            horizon_days: number;
            /**
             * Var
             * @description Loss threshold, reported as a positive number
             */
            var: number;
            /**
             * Expected Shortfall
             * @description Mean loss beyond VaR, positive number
             */
            expected_shortfall: number;
            /** Portfolio Value */
            portfolio_value: number;
            /**
             * Var Pct
             * @description VaR as a fraction of net portfolio value
             */
            var_pct: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ZeroPointOut */
        ZeroPointOut: {
            /** Maturity */
            maturity: number;
            /**
             * Zero Rate
             * @description Continuously compounded
             */
            zero_rate: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    black_scholes_api_v1_pricing_black_scholes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlackScholesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlackScholesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    implied_volatility_api_v1_pricing_implied_volatility_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImpliedVolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpliedVolResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bond_api_v1_pricing_bond_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BondRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BondResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bootstrap_api_v1_pricing_yield_curve_bootstrap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parametric_var_api_v1_risk_var_parametric_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParametricVaRRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VaRResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    historical_var_api_v1_risk_var_historical_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoricalVaRRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VaRResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monte_carlo_var_api_v1_risk_var_monte_carlo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonteCarloVaRRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VaRResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_v1_stress_test_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOut"][];
                };
            };
        };
    };
    run_stress_test_api_v1_stress_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StressTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StressTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimize_api_v1_portfolio_optimize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    frontier_api_v1_portfolio_frontier_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrontierRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrontierResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
